/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import com.mycompany.curriculumdigital.User;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import p2p.IremoteP2P;
import java.rmi.Naming;
import java.security.PrivateKey;

/**
 *
 * @author Gui
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    IremoteP2P myremoteObject;
    String instPassword;
    String userPassword;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLoginUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowPubKey = new javax.swing.JTextArea();
        txtPasswordLogin = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtInstitutionLogin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLoginInstituicao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PasswordInstitutionLogin = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInstRegister = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRegisterPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jCheckBoxUser = new javax.swing.JCheckBox();
        jCheckBoxInstituicao = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jAddressServer = new javax.swing.JTextField();
        jConnectServer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome da instituição");

        txtUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        jLoginUser.setText("Login");
        jLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginUserActionPerformed(evt);
            }
        });

        ShowPubKey.setColumns(20);
        ShowPubKey.setRows(5);
        jScrollPane1.setViewportView(ShowPubKey);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Nota: A app vem sem users criados crie dois users para experimentar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUserLogin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLoginUser, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txtPasswordLogin))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(24, 24, 24))
        );

        jTabbedPane4.addTab("Utilizador", new javax.swing.ImageIcon(getClass().getResource("/images/permission.png")), jPanel2); // NOI18N

        txtInstitutionLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstitutionLoginActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome da instituição");

        jLabel8.setText("Password");

        jLoginInstituicao.setText("Login");
        jLoginInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginInstituicaoActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        PasswordInstitutionLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordInstitutionLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInstitutionLogin)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLoginInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(PasswordInstitutionLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInstitutionLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(17, 17, 17)
                        .addComponent(PasswordInstitutionLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLoginInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Instituição", new javax.swing.ImageIcon(getClass().getResource("/images/banco.png")), jPanel1); // NOI18N

        jLabel3.setText("Nome ");

        jLabel4.setText("Password");

        txtInstRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstRegisterActionPerformed(evt);
            }
        });

        btRegister.setText("Register");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        jLabel5.setText("Confirm password");

        txtRegisterPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterPasswordActionPerformed(evt);
            }
        });

        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });

        jCheckBoxUser.setText("Utilizador");
        jCheckBoxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUserActionPerformed(evt);
            }
        });

        jCheckBoxInstituicao.setText("Instituição");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(txtInstRegister)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(btRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRegisterPassword)
                        .addComponent(txtConfirmPassword))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInstRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxUser)
                    .addComponent(jCheckBoxInstituicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Register", new javax.swing.ImageIcon(getClass().getResource("/images/adicionar-usuario.png")), jPanel3); // NOI18N

        jAddressServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddressServerActionPerformed(evt);
            }
        });

        jConnectServer.setText("Conectar");
        jConnectServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectServerActionPerformed(evt);
            }
        });

        jLabel9.setText("Coloque o address do servidor:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jConnectServer)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddressServer, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(147, 147, 147))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddressServer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConnectServer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Conectar ao Servidor", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jLoginInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginInstituicaoActionPerformed
        try {
            // Verifica se o objeto remoto está conectado
            if (myremoteObject == null) {
                JOptionPane.showMessageDialog(this, "Conecte-se ao servidor antes de fazer login.");
                return;
            }

            String nome = txtInstitutionLogin.getText();
            String password = new String(PasswordInstitutionLogin.getPassword());

            boolean loginSuccess = myremoteObject.loginInstituicao(nome, password);
            if (loginSuccess) {
                JOptionPane.showMessageDialog(this, "Login bem-sucedido!");
                instPassword = new String(password);
                new InstituicaoGUI(new User(nome), instPassword, myremoteObject).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Instituição não existe ou senha incorreta.");
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao tentar fazer login.");
        }

    }//GEN-LAST:event_jLoginInstituicaoActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void txtRegisterPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterPasswordActionPerformed
        // TODO add your handling code heretxtUserLogi
    }//GEN-LAST:event_txtRegisterPasswordActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed

        char[] password = txtRegisterPassword.getPassword();
        char[] confirmPassword = txtConfirmPassword.getPassword();
        String nome = txtInstRegister.getText();

        // Verifica se as senhas coincidem
        if (!Arrays.equals(password, confirmPassword)) {
            JOptionPane.showMessageDialog(this, "As passwords têm que ser iguais");
            return;  // Sai da função se as senhas não forem iguais
        }

        // Verifica se uma das checkboxes está selecionada
        if (!jCheckBoxUser.isSelected() && !jCheckBoxInstituicao.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecione se é um utilizador ou uma instituição");
            return;  // Sai da função se nenhuma checkbox estiver selecionada
        }

        try {
            // Gera o par de chaves
            KeyPairGenerator keyGen = KeyPairGenerator.getInstance("RSA");
            keyGen.initialize(2048);
            KeyPair pair = keyGen.generateKeyPair();
            PublicKey publicKey = pair.getPublic();
            PrivateKey privateKey = pair.getPrivate();

            // Salva a chave privada localmente
            User user = new User(nome);
            user.setPriv(privateKey);
            user.setPub(publicKey);
            user.generateKeys(); // Gera a chave simétrica
            user.save(new String(password));

            // Registra o usuário no servidor remoto
            if (jCheckBoxUser.isSelected()) {
                myremoteObject.registerUser(nome, publicKey, new String(password));
                JOptionPane.showMessageDialog(this, "Utilizador criado com sucesso!");
            } else if (jCheckBoxInstituicao.isSelected()) {
                myremoteObject.registerInstituicao(nome, publicKey, new String(password));
                JOptionPane.showMessageDialog(this, "Instituição criada com sucesso!");
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private void txtInstRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstRegisterActionPerformed

    private void jLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginUserActionPerformed
        // TODO add your handling code here:
        try {
            String nome = txtUserLogin.getText();
            String password = new String(txtPasswordLogin.getPassword());

            boolean loginSuccess = myremoteObject.loginUtilizador(nome, password);
            if (loginSuccess) {
                JOptionPane.showMessageDialog(this, "Login bem-sucedido!");
                // Carregar a interface do utilizador ou outra ação pós-login
                userPassword = new String(password);
                new UtilizadorGUI(new User(nome), userPassword, myremoteObject).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Utilizador não existe ou senha incorreta.");
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao tentar fazer login.");
        }
    }//GEN-LAST:event_jLoginUserActionPerformed

    private void txtUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserLoginActionPerformed

    private void txtInstitutionLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstitutionLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstitutionLoginActionPerformed

    private void jCheckBoxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxUserActionPerformed

    private void jAddressServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddressServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddressServerActionPerformed

    private void jConnectServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectServerActionPerformed
        try {
            String address = jAddressServer.getText();
            System.out.println("Tentando conectar ao endereço: " + address);  // Depuração

            // Substitua "RemoteObject" pelo nome do objeto remoto registrado no servidor
            myremoteObject = (IremoteP2P) Naming.lookup(address);

            if (myremoteObject != null) {
                System.out.println("Conectado ao objeto remoto com sucesso!");
                JOptionPane.showMessageDialog(this, "Conectado ao servidor com sucesso!");
            }
        } catch (Exception ex) {
            System.out.println("Erro ao tentar conectar: " + ex.getMessage());  // Depuração de erro
            ex.printStackTrace();  // Exibe a stack trace para entender o erro
            JOptionPane.showMessageDialog(this, "Erro ao tentar conectar: " + ex.getMessage());
        }
    }//GEN-LAST:event_jConnectServerActionPerformed

    private void PasswordInstitutionLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordInstitutionLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordInstitutionLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordInstitutionLogin;
    private javax.swing.JTextArea ShowPubKey;
    private javax.swing.JButton btRegister;
    private javax.swing.JTextField jAddressServer;
    private javax.swing.JCheckBox jCheckBoxInstituicao;
    private javax.swing.JCheckBox jCheckBoxUser;
    private javax.swing.JButton jConnectServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginInstituicao;
    private javax.swing.JButton jLoginUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtInstRegister;
    private javax.swing.JTextField txtInstitutionLogin;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JPasswordField txtRegisterPassword;
    private javax.swing.JTextField txtUserLogin;
    // End of variables declaration//GEN-END:variables
}
